FROM debian:stable-20200803-slim
MAINTAINER https://github.com/underworldcode/stripy
ENV IMAGENAME=underworldcode/py3-lavavu-notebook-bundle
ENV PROJ_NAME=py3-lavavu-notebook-bundle

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        bash-completion \
        build-essential \
        gfortran \
        git \
        python3-dev \
        python3-pip \
        python3-tk \
        python3-h5py \
        python3-lxml \
        python3-gdal \
        libxml2-dev \
        xorg-dev \
        ssh \
        libfreetype6-dev \
        libpng-dev \
        libxft-dev \
        xvfb \
        freeglut3-dev \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        rsync \
        vim \
        less \
        xauth \
        swig \
        gdb-minimal \
        cython \
        cmake \
        gdal-bin \
        libgeos++ \
        libgeos-dev \
        libgdal-dev \
        libproj-dev \
        libproj-dev \
        proj-bin \
        curl \
        zip \
        pandoc \
        wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN alias python=python3
# Upgrade and install python packages

RUN python3 -m pip install --no-cache-dir setuptools wheel && \
    python3 -m pip install --upgrade --no-cache-dir Cython numpy scipy matplotlib && \
    python3 -m pip install --no-cache-dir \
    packaging \
    appdirs \
    gdal \
    pyvirtualdisplay \
    jupyter \
    jupyterlab \
    pyproj \
    pyepsg \
    cartopy \
    obspy \
    seaborn \
    pandas \
    xarray \
    h5netcdf \
    stripy \
    litho1pt0 \
    lavavu && \
    USE_SETUPCFG=0 \
    HDF5_INCDIR=/usr/include/hdf5/serial \
    HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial \
    python3 -m pip install --no-cache-dir git+https://github.com/Unidata/netcdf4-python

# previously lavavu==1.2.52


RUN python3 -m pip  install shapely --no-binary shapely --upgrade --no-cache-dir --force-reinstall


# Jovyan user / group

ENV NB_USER jovyan
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER} || true  # dont worry about the error ... keep building

RUN addgroup jovyan  || true
RUN usermod -a -G jovyan jovyan || true


# LavaVu stuff
# script for xvfb-run.  all docker commands will effectively run under this via the entrypoint
RUN printf "#\041/bin/sh \n rm -f /tmp/.X99-lock && xvfb-run -s '-screen 0 1600x1200x16' \$@" >> /usr/local/bin/xvfbrun.sh && \
chmod +x /usr/local/bin/xvfbrun.sh


# Add Tini
EXPOSE 8888
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
RUN chmod +x /usr/local/bin/tini
ENTRYPOINT ["/usr/local/bin/tini", "--"]

WORKDIR /home/jovyan
