#################################################
#  Short docker file to distribute some notebooks
#################################################

ARG FROMIMG_ARG=underworldcode/py3-lavavu-notebook-bundle:0.9.4-debian
FROM ${FROMIMG_ARG}

##################################################
# Non standard as the files come from the packages

USER root

RUN mkdir -p /home/user_data && chmod +rx /home/user_data && chown jovyan:jovyan /home/user_data
WORKDIR /home/user_data

### Stripy - Notebooks

RUN python3 -m pip uninstall stripy --yes
ENV MODULE_DIR="stripy-src"
ADD --chown=jovyan:jovyan . / stripy-src/
RUN   cd $MODULE_DIR && python3 -m pip install --no-cache-dir --no-deps --upgrade .


# This should overwrite any existing Notebooks directory

RUN ipython3 -c 'import stripy; stripy.documentation.install_documentation(path="Notebooks")'


RUN python3 -m pip install --no-cache-dir --upgrade \
    jupyterhub \
    pytest \
    imageio \
    litho1pt0 \
    git+https://github.com/OKaluza/LavaVu.git@afa8cd24e6dae7ffbacf9735db8e1affd85fd3df


# Find a place to keep /home/jovyan in the container for khub

RUN mkdir -p /home/jovyan/STRIPY && chmod +rx /home/jovyan/STRIPY && chown jovyan:jovyan /home/jovyan/STRIPY
RUN ln -s /home/user_data/Notebooks /home/jovyan/STRIPY/Notebooks
ADD --chown=jovyan:jovyan  Docker/install_notebooks.py /home/user_data/scripts/install_notebooks.py

WORKDIR  /home/jovyan/
ENV NB_USER jovyan
USER jovyan


# Run PyTest
############

RUN cd $MODULE_DIR/tests && pytest *.py

# Non standard as the files come from the packages
##################################################

## These are supplied by the build script
## build-dockerfile.sh

ARG IMAGENAME_ARG
ARG PROJ_NAME_ARG=stripy
ARG NB_PORT_ARG=8888
ARG NB_PASSWD_ARG=""
ARG NB_DIR_ARG="Notebooks"
ARG START_NB_ARG="0-StartHere.ipynb"

# The args need to go into the environment so they
# can be picked up by commands/templates (defined previously)
# when the container runs

ENV IMAGENAME=$IMAGENAME_ARG
ENV PROJ_NAME=$PROJ_NAME_ARG
ENV NB_PORT=$NB_PORT_ARG
ENV NB_PASSWD=$NB_PASSWD_ARG
ENV NB_DIR=$NB_DIR_ARG
ENV START_NB=$START_NB_ARG


# Trust all notebooks
# RUN find -name \*.ipynb  -print0 | xargs -0 jupyter trust


# expose notebook port server port
EXPOSE $NB_PORT

VOLUME /home/jovyan/$NB_DIR/user_data

# note we use xvfb which to mimic the X display for lavavu
ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]

# launch notebook
ADD --chown=jovyan:jovyan Docker/scripts/run-jupyter.sh scripts/run-jupyter.sh
CMD scripts/run-jupyter.sh
