# Book settings
title: Stripy
author: Louis Moresi, Ben Mather
# logo: Diagrams/MundusSubterraneus.png
# exclude_patterns: ["README.md", "Notes/*", "Scripts/*"]

latex:
  latex_documents:
    targetname: Stripy.tex

html:
#  home_page_in_navbar option: true
  extra_navbar: <button type="button" onclick="legibleFontSwitcher()">Switch Font</button>&nbsp;&nbsp;<button type="button" onclick="fontScaler(1.1)">&#10133;</button><button type="button" onclick="fontScaler(0.0)">&#9679;</button><button type="button" onclick="fontScaler(0.909)">&#10134;</button>  
  use_repository_button: true

parse:
  myst_extended_syntax: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


repository:
  url                       : "https://github.com/underworldcode/stripy"  # Online location of your book's source code
  path_to_book              : "jupyterbook/"
  branch                    : "dev"                                    # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  # jupyterhub_url: "https://phys3070.rses.geoscience.education"  # The URL for your JupyterHub. 
  notebook_interface: "classic"           # "jupyterlab" or "classic"
  binderhub_url:  "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : true 

execute:
  execute_notebooks: 'auto'
  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  timeout: 180



