# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test stripy

on:
  push:
  release:
  workflow_dispatch:

jobs:
  build:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.3.1-0"
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            numpy
            scipy
            pytest
            fortran-compiler
            build
            meson
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: "all"

      - name: Install current gplately
        run: |
          pip install . --no-binary :all: --no-cache-dir --no-dependencies

      - name: Test with pytest
        run: |
          python -m pytest -vv stripy/tests